name: admin_app
description: Admin Dashboard (Flutter Web) for the RWA platform.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.6.0
  go_router: ^14.2.0
  flutter_secure_storage: ^9.2.2
  
  # Charts and Analytics
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.2.5
  syncfusion_flutter_maps: ^27.2.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

