name: agent_app
description: RWA Agent Portal - Mobile-first verification agent application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-127.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  
  # HTTP & API
  dio: ^5.9.0
  dio_web_adapter: ^2.1.1
  
  # Secure Storage
  flutter_secure_storage: ^9.2.4
  
  # Location & GPS
  geolocator: ^13.0.1
  location: ^7.1.0
  geocoding: ^3.0.0
  
  # Camera & Media
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  photo_manager: ^3.5.0
  video_player: ^2.9.2
  
  # File Management
  path_provider: ^2.1.5
  file_picker: ^8.1.6
  
  # Local Storage & Offline
  sqflite: ^2.4.1
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.1
  
  # Navigation
  go_router: ^14.8.1
  
  # UI & Animations
  lottie: ^3.1.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.6
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Maps & Navigation
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700