version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rwa
      POSTGRES_PASSWORD: rwa
      POSTGRES_DB: rwa
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DATABASE_URL: postgres://rwa:rwa@db:5432/rwa
      JWT_SECRET: dev_secret
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  db_data:









